# Generated by Django 2.0.5 on 2018-05-21 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated', models.BooleanField(default=False)),
                ('isNew', models.BooleanField(default=False)),
                ('article_title', models.TextField()),
                ('subject', models.TextField()),
                ('company', models.TextField()),
                ('publication_title', models.TextField()),
                ('publication_date', models.DateField(null=True)),
                ('publication_subject', models.TextField()),
                ('source_type', models.TextField()),
                ('document_type', models.TextField()),
                ('html', models.TextField()),
                ('ratedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
