# Generated by Django 2.0.5 on 2018-06-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_doc', '0002_auto_20180521_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='isNew',
        ),
        migrations.AddField(
            model_name='doc',
            name='aboutProductApproval',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=20, verbose_name='Is this article about an approval for a product?'),
        ),
        migrations.AddField(
            model_name='doc',
            name='aboutProductLaunch',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=20, verbose_name='Is this article specifically about a product launch?'),
        ),
        migrations.AddField(
            model_name='doc',
            name='mentionsProduct',
            field=models.CharField(blank=True, choices=[('title', 'Article title'), ('subject', 'Subject section'), ('body', 'Main body of the text')], max_length=20, verbose_name='If the article mentions the product by name, where is the mention?'),
        ),
    ]
