# Generated by Django 2.0.5 on 2018-06-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_doc', '0003_auto_20180603_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='ifProductInBodyWhere',
            field=models.TextField(blank=True, max_length=20, verbose_name='If the product is mentioned in the body, approximately where is it mentioned?'),
        ),
    ]
