# Generated by Django 2.0.5 on 2018-06-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_doc', '0004_doc_ifproductinbodywhere'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='otherCompany',
            field=models.TextField(blank=True, max_length=100, verbose_name='What other companies are mentioned in the article?'),
        ),
        migrations.AddField(
            model_name='doc',
            name='otherProduct',
            field=models.TextField(blank=True, max_length=100, verbose_name='What other products are mentioned in the article?'),
        ),
        migrations.AddField(
            model_name='doc',
            name='subjectCompany',
            field=models.TextField(blank=True, max_length=100, verbose_name='What company is the article about, if any?'),
        ),
        migrations.AddField(
            model_name='doc',
            name='subjectProduct',
            field=models.TextField(blank=True, max_length=100, verbose_name='If the product is mentioned anywhere, what is its name?'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='ifProductInBodyWhere',
            field=models.TextField(blank=True, max_length=100, verbose_name='If the product is mentioned in the body, approximately where is it mentioned?'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='mentionsProduct',
            field=models.CharField(blank=True, choices=[('title', 'Article title'), ('subject', 'Subject section'), ('body', 'Main body of the text')], max_length=20, verbose_name='If the article mentions the product by name, where is it mentioned?'),
        ),
    ]
