# Generated by Django 2.0.5 on 2018-06-05 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate_doc', '0005_auto_20180603_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='assignedTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doc',
            name='ifProductInBodyWhere',
            field=models.CharField(blank=True, max_length=200, verbose_name='If the product is mentioned in the body, approximately where is it mentioned?'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='otherCompany',
            field=models.CharField(blank=True, max_length=200, verbose_name='What other companies are mentioned in the article?'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='otherProduct',
            field=models.CharField(blank=True, max_length=200, verbose_name='What other products are mentioned in the article?'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='subjectCompany',
            field=models.CharField(blank=True, max_length=200, verbose_name='What company is the article about, if any?'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='subjectProduct',
            field=models.CharField(blank=True, max_length=200, verbose_name='If the product is mentioned anywhere, what is its name?'),
        ),
    ]
