# Generated by Django 2.0.5 on 2018-06-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_doc', '0006_auto_20180605_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='aboutProductApproval',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='aboutProductLaunch',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='assignedTo',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='ifProductInBodyWhere',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='mentionsProduct',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='otherCompany',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='otherProduct',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='ratedBy',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='subjectCompany',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='subjectProduct',
        ),
        migrations.AddField(
            model_name='doc',
            name='articleTopic',
            field=models.CharField(blank=True, choices=[('launch', 'Product Launch'), ('fdaApproval', 'FDA Approval'), ('neither', 'Neither')], max_length=20, verbose_name='What is this article mainly about?'),
        ),
        migrations.AddField(
            model_name='doc',
            name='companyName',
            field=models.CharField(blank=True, max_length=200, verbose_name='If the article is about a product launch or FDA approval, what is the name of the company which launched the product or acquired approval?'),
        ),
        migrations.AddField(
            model_name='doc',
            name='countryOfLaunch',
            field=models.CharField(blank=True, max_length=200, verbose_name='If the article is about a product launch, what is the country in which the launch took place, if mentioned? '),
        ),
        migrations.AddField(
            model_name='doc',
            name='dateOfApprovalOrLaunch',
            field=models.CharField(blank=True, max_length=200, verbose_name='If the article is about a product launch or FDA approval, what is the date of the launch or approval, if mentioned?'),
        ),
        migrations.AddField(
            model_name='doc',
            name='otherProducts',
            field=models.CharField(blank=True, max_length=200, verbose_name='What other products are mentioned in the article, if any? Please separate multiple answers by commas.'),
        ),
        migrations.AddField(
            model_name='doc',
            name='productName',
            field=models.CharField(blank=True, max_length=200, verbose_name='If the article is about a product launch or FDA approval, what is the name of the product? Please separate multiple answers by commas.'),
        ),
    ]
