# Generated by Django 2.0.5 on 2018-06-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_doc', '0007_auto_20180606_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='otherCompanies',
            field=models.CharField(blank=True, max_length=200, verbose_name='What other companies are mentioned in the article, if any? Please separate multiple answers by commas.'),
        ),
    ]
